// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX6Vi6MBxmKiylFDZLt975trWQwje-rm0',
    appId: '1:710027462041:web:b4a38f30a475ccb9c27f08',
    messagingSenderId: '710027462041',
    projectId: 'gameofthrones-d302c',
    authDomain: 'gameofthrones-d302c.firebaseapp.com',
    storageBucket: 'gameofthrones-d302c.appspot.com',
    measurementId: 'G-XD49309X3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbOucoP41xrqw21Hv9tTVkXZgJ_8p-fM4',
    appId: '1:710027462041:android:a74b5592cbb4a5d7c27f08',
    messagingSenderId: '710027462041',
    projectId: 'gameofthrones-d302c',
    storageBucket: 'gameofthrones-d302c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCaZ8dGRqa4mAbWmxeCc_BY_OIVH0tmhk',
    appId: '1:710027462041:ios:6ef54b8a56e016a4c27f08',
    messagingSenderId: '710027462041',
    projectId: 'gameofthrones-d302c',
    storageBucket: 'gameofthrones-d302c.appspot.com',
    iosBundleId: 'com.example.gameofthronesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCaZ8dGRqa4mAbWmxeCc_BY_OIVH0tmhk',
    appId: '1:710027462041:ios:9f6c764b25aea9bcc27f08',
    messagingSenderId: '710027462041',
    projectId: 'gameofthrones-d302c',
    storageBucket: 'gameofthrones-d302c.appspot.com',
    iosBundleId: 'com.example.gameofthronesapp.RunnerTests',
  );
}
